# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://www.adityaambasth.in #http://localhost:3000 
baseurl: /
title: Aditya Ambasth
author: Aditya Ambasth
description: Personal blog and resume
avatar: profile.png
email: aditya.ada@hotmail.com
github: https://github.com/AdityaAmbasth # username
twitter: https://twitter.com/Aditya_Ada
linkedin: https://in.linkedin.com/in/ambasthaditya
stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
disqus: aditya_ambasth
google_analytics: UA-69391421-1
comment : true

# needed for travis-ci build
exclude: [vendor]
